version: "3"
services:
  api:
    build: .
    ports:
      - "80:5000"
    networks:
      - resign-network

  redis:
    image: redis:alpine
    container_name: redisqueue.resign
    ports:
      - "6379"
    networks:
      - resign-network
      
networks:
  resign-network:
